export enum PharmacyType {
	RETAIL = 'RETAIL',
	HOSPITAL = 'HOSPITAL',
	COMPOUNDING = 'COMPOUNDING',
	ONLINE = 'ONLINE',
}

export enum PharmacyStatus {
	HOLD = 'HOLD',
	ACTIVE = 'ACTIVE',
	CLOSED = 'CLOSED',
	DELETE = 'DELETE',
}

export enum PharmacyLocation {
	DOWNTOWN = 'DOWNTOWN',
	NORTH_SIDE = 'NORTH_SIDE',
	SOUTH_SIDE = 'SOUTH_SIDE',
	EAST_SIDE = 'EAST_SIDE',
	WEST_SIDE = 'WEST_SIDE',
	CENTRAL = 'CENTRAL',
}
